/**
 * Slug-specific FAQ schema data for blog posts.
 * Used to inject FAQPage JSON-LD without changing visible content.
 */

type FaqEntry = { question: string; answer: string };

export const BLOG_FAQ_SCHEMAS: Record<string, FaqEntry[]> = {
  "is-it-worth-buying-presale-condo-2026": [
    { question: "Are presale deposits safe if a developer goes bankrupt?", answer: "Yes, in British Columbia, your presale deposit is held in a lawyer's or notary's trust account. It is not used by the developer to fund construction. If the project is canceled, your deposit is returned to you." },
    { question: "Should I sell or keep and rent out my presale condo upon completion?", answer: "Given the strong rental demand and the projected decrease in housing starts over the next few years, holding the property and renting it out is generally the stronger wealth-building strategy. Flipping the contract (assignment) is possible, but it subjects you to assignment fees and potential taxes." },
    { question: "What are the real risks of buying a presale condo?", answer: "The primary risks are construction delays and changes to the final product. This is why developer reputation is the single most important factor in the selection process." },
    { question: "Is it worth buying a presale condo in 2026?", answer: "With the Bank of Canada holding rates at 2.25%, developer incentives up to $18,000, and the new First-Time Home Buyers' GST rebate saving up to $50,000, the math currently favors strategic presale buyers — especially in Surrey and Langley where inventory is high and prices start under $300,000." },
  ],

  "presale-condo-faq": [
    { question: "What is a presale condo?", answer: "A presale condo is a unit you purchase directly from a developer before construction is complete. You buy based on floor plans, renderings, and a legal Disclosure Statement. The building is then constructed over 2.5 to 4 years, after which you take possession of your brand-new home." },
    { question: "How much does it cost to work with a presale agent?", answer: "It costs you absolutely nothing. Developers pay real estate agent commissions when a presale unit is sold. Our job is to represent you — negotiate on your behalf, review your Disclosure Statement, guide you through deposits and completion — all at zero cost to you." },
    { question: "What is the typical deposit for a presale condo in BC?", answer: "Deposits typically range from 5% to 10% at signing, with additional deposits due at construction milestones. Total deposits usually add up to 10-20% of the purchase price, spread across several installments over 6 to 18 months. All deposits are held in a lawyer's trust account — not by the developer." },
    { question: "How long does it take for a presale condo to be built?", answer: "Most presale condos in BC take 2.5 to 4 years from purchase to completion. Concrete high-rises tend to take longer (3-4 years), while wood-frame low-rises and townhomes can be completed in 2-3 years. Delays of 6-12 months are not uncommon." },
    { question: "What is the 7-day rescission period?", answer: "BC law gives you seven calendar days after signing a presale agreement to cancel the deal and get your deposit back — no questions asked, no penalties. This is mandated by the Real Estate Development Marketing Act (REDMA) and is one of the strongest buyer protections in Canada." },
    { question: "What is an assignment sale?", answer: "An assignment sale is when you sell your rights to a presale contract to another buyer before the building is completed. You are not selling property — you are selling your contract. The new buyer steps into your shoes and completes the purchase. Many presale contracts allow assignments, though some developers charge a fee or require approval." },
    { question: "What happens if the developer cancels the project?", answer: "If a developer cancels a presale project, you receive a full refund of all deposits. Your money has been sitting in a lawyer's trust account, protected from the developer's creditors. While you lose the opportunity cost of having funds tied up, your principal is completely safe." },
    { question: "Do I need mortgage pre-approval to buy presale?", answer: "Mortgage pre-approval is not required at signing, but it is strongly recommended. Pre-approval helps you understand your purchasing power and budget. Your final mortgage will not be arranged until closer to completion — potentially 2-4 years later — so rates and qualifying criteria may change." },
    { question: "What warranty comes with a new presale condo in BC?", answer: "All new homes in BC come with mandatory warranty coverage under the Homeowner Protection Act: 2 years for materials and labour defects, 5 years for the building envelope (water penetration), and 10 years for structural defects. This is administered through BC Housing." },
    { question: "What are the risks of buying presale?", answer: "The main risks include construction delays (completion dates can shift by months or years), market uncertainty (property values could decrease during construction), interest rate changes (mortgage rates at completion may be higher), inability to inspect the finished unit, and developer risk (though rare, developers can face financial difficulties). These risks are manageable with proper planning and professional guidance." },
    { question: "Can I customize my presale condo?", answer: "Yes. Most developers offer a colour and finish selection appointment during construction. You can usually choose from 2-3 colour palettes for kitchen cabinetry, countertops, flooring, and bathroom tiles and fixtures. Some developers offer upgrade packages for an additional cost." },
  ],

  "presale-condo-deposit-structure-bc": [
    { question: "What is a presale deposit?", answer: "A presale deposit is the money you pay between signing your Contract of Purchase and Sale and the completion of the building. It is held in a lawyer's trust account and shows the developer you are committed. It is not the same as a mortgage down payment — your deposits are applied toward your total down payment at completion." },
    { question: "How much deposit do I need for a presale condo in BC?", answer: "Most BC presale condos require total deposits of 10% to 20% of the purchase price. However, many projects — especially during promotional periods — offer deposits as low as 5% to 10%. The deposit percentage depends on the developer's requirements, market conditions, VIP incentives, and your agent's ability to negotiate." },
    { question: "How are presale deposit payments structured?", answer: "Unlike resale purchases where you bring a lump sum at closing, presale deposits are spread across multiple installments. For example, on a $500,000 condo at 15% total deposit: 2.5% ($12,500) at signing, 2.5% ($12,500) at 30 days, 5% ($25,000) at 120 days, and 5% ($25,000) at 365 days. Your actual upfront cash requirement at signing is just $12,500." },
    { question: "How are presale deposits protected in BC?", answer: "All presale deposits in BC are protected under the Real Estate Development Marketing Act (REDMA). Deposits are held in a lawyer's trust account — not by the developer. The developer cannot access your deposit until specific legal conditions are met, and if the project is cancelled, you receive a full refund of all deposits." },
    { question: "What happens to my deposit if the presale project is cancelled?", answer: "If a developer cancels a presale project, you are entitled to a full refund of all deposits. The money has been sitting in a trust account, protected from the developer's creditors. You will not earn interest on the funds in most cases, but your principal is safe." },
    { question: "Can I use my RRSP or FHSA for a presale deposit?", answer: "Yes. The First Home Savings Account (FHSA) lets you contribute up to $8,000 per year (lifetime max $40,000) with tax-deductible contributions and tax-free withdrawals for a first home. The RRSP Home Buyers' Plan (HBP) lets you withdraw up to $35,000 tax-free. A couple can potentially access up to $150,000 in tax-advantaged savings combining both programs." },
  ],

  "presale-vs-resale-condo-bc": [
    { question: "What is the difference between a presale and a resale condo?", answer: "A presale condo is purchased from a developer before construction is complete — you buy based on floor plans and wait 2.5 to 4 years before moving in. A resale condo is an existing unit being sold by a current owner — you can tour the actual unit and typically move in within 30 to 90 days of purchase." },
    { question: "What are the advantages of buying a presale condo?", answer: "Presale advantages include: locking in today's price and benefiting from appreciation during construction, brand new appliances and finishes with a 2-5-10 year warranty, flexible staggered deposit structure (5-20% spread over months), customization of colours and finishes, assignment potential to sell your contract before completion, and VIP pricing with early-buyer incentives." },
    { question: "What are the advantages of buying a resale condo?", answer: "Resale advantages include: immediate occupancy (move in within weeks), ability to walk through and inspect the actual unit, established neighbourhood with existing amenities and transit, more room for price negotiation, no construction risk or delays, and access to years of strata minutes and financial history." },
    { question: "Who should buy a presale condo?", answer: "Presale is ideal if you are not in a rush to move, want to lock in pricing before further appreciation, value new construction with warranty protection, are an investor looking for appreciation potential, want lower initial deposits spread over time, or are a first-time buyer using FHSA or RRSP HBP savings." },
    { question: "Who should buy a resale condo?", answer: "Resale is better if you need to move soon (relocating, upsizing, or downsizing), want to see exactly what you are buying, prefer an established neighbourhood with proven amenities, are uncomfortable with construction delays or uncertainty, or want to negotiate on price." },
    { question: "What is the BC Home Flipping Tax?", answer: "As of 2025, BC's Home Flipping Tax applies a 20% tax on profits from properties sold within one year of purchase, declining to 0% at two years. This applies to both presale assignments and resale flips. If you assign your presale contract within two years of the original purchase date, the flipping tax may apply to your profit." },
  ],

  "gst-rebate-presale-condos-bc-2026": [
    { question: "What is the new First-Time Home Buyers' GST rebate?", answer: "As of March 17, 2026, eligible first-time home buyers receive a full rebate of the 5% GST on newly constructed homes priced up to $1,000,000. For homes between $1,000,000 and $1,500,000, a partial rebate is available. The maximum rebate is capped at $50,000." },
    { question: "What happens if the developer refuses to credit the rebate at closing?", answer: "If the builder does not credit the rebate, you must pay the GST upfront and apply for the rebate directly through your CRA account or by mailing Form GST190. You generally have two years from the date of possession to apply." },
    { question: "Does the GST rebate apply to presale assignments?", answer: "If you purchase a presale assignment (taking over someone else's contract before completion), you are still considered the first purchaser from the builder upon completion. As long as you meet the first-time buyer criteria, you are eligible for the rebate on the final purchase price." },
    { question: "Can I rent out the condo and still get the GST rebate?", answer: "No. To qualify for the First-Time Home Buyers' GST/HST Rebate, the property must be your primary residence. If your intent is to rent the unit out immediately, you will not qualify for this specific rebate, though you may qualify for the New Residential Rental Property Rebate instead." },
    { question: "How much can a first-time buyer save combining GST rebate and PTT exemption?", answer: "A first-time buyer purchasing a $650,000 presale condo can save a total of $43,500 in taxes at closing by combining the full GST rebate ($32,500) with the Property Transfer Tax exemption ($11,000)." },
  ],

  "how-to-buy-presale-condo-bc": [
    { question: "What does presale mean?", answer: "A presale condo (also called pre-construction or pre-build) is a unit you purchase directly from a developer before the building is finished. You buy based on architectural plans, floor plan layouts, renderings, and a Disclosure Statement. In BC, presale purchases are governed by the Real Estate Development Marketing Act (REDMA), which provides significant buyer protections." },
    { question: "What are the steps to buy a presale condo in BC?", answer: "The process includes: (1) Research your budget, location, and timeline. (2) Get mortgage pre-approval to understand purchasing power. (3) Register for VIP access to get first pick of units and best pricing. (4) Review the Disclosure Statement. (5) Choose your unit and sign the Contract of Purchase and Sale. (6) Use the 7-day rescission period to have a lawyer review. (7) Pay staggered deposits over several months. (8) Wait for construction (2.5-4 years). (9) Complete and close — arrange your mortgage, do a walkthrough inspection, and get your keys." },
    { question: "What is the 7-day rescission period for presale condos?", answer: "BC law gives you seven calendar days after signing to cancel the contract and receive a full refund of any deposits — no questions asked, no penalties. Use this time to have a lawyer review the contract, confirm your financing, and sleep on the decision." },
    { question: "How much deposit do I need for a presale condo?", answer: "Presale deposits in BC typically range from 5% to 20% of the purchase price, paid in staggered installments over several months. For example, on a $600,000 unit: $15,000 (2.5%) at signing, $15,000 (2.5%) at 30 days, $30,000 (5%) at 120 days, and $30,000 (5%) at 365 days — totalling $90,000 (15%). All deposits are held in a lawyer's trust account." },
    { question: "What are the closing costs for a presale condo in BC?", answer: "Closing costs include: legal fees ($1,500-$2,500), Property Transfer Tax (1% on first $200K, 2% on $200K-$2M — first-time buyers may be exempt on homes up to $835,000), GST (5% on new construction with potential rebates), strata fees starting at completion, and home insurance. For a $600,000 presale condo, budget approximately $68,000-$135,000 total including deposits and closing costs." },
    { question: "What are the benefits of buying a presale condo?", answer: "Key benefits include: price lock (lock in today's price and benefit from appreciation during construction), 2-5-10 year warranty coverage mandated by BC law, brand new appliances and finishes, customization options for colour schemes, flexible staggered deposit payments, and assignment potential to sell your contract before completion." },
    { question: "What are the risks of buying presale?", answer: "Risks include: construction delays (completions can be delayed by months or years), market changes (property values could decrease), interest rate risk (rates at completion may be higher), differences from renderings, and developer risk (rare but developers can face financial difficulties)." },
  ],
};
