project_id = "thvlisplwqhtjpzpedhq"

[functions.send-lead-notification]
verify_jwt = false

[functions.check-expiring-listings]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-project-lead]
verify_jwt = false

[functions.parse-project-brochure]
verify_jwt = false

[functions.sort-project-images]
verify_jwt = false

[functions.fetch-drive-folder]
verify_jwt = false
