/**
 * approve-lead-link
 * ─────────────────────────────────────────────────────────────
 * Public GET endpoint that lets an admin approve or reject a lead by clicking
 * a signed link in the notification email. No login required — security is
 * enforced via HMAC-signed tokens that include leadId, action, and an expiry.
 *
 *   GET /functions/v1/approve-lead-link?token=<base64url>
 *
 * Token payload (base64url JSON):
 *   { leadId: uuid, action: "approve" | "reject", exp: unix-seconds }
 * Signed with HMAC-SHA256 using SUPABASE_SERVICE_ROLE_KEY as the key.
 *
 * Returns a small HTML page confirming the action.
 */

import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, OPTIONS",
};

function b64urlDecode(str: string): Uint8Array {
  const pad = str.length % 4 === 0 ? "" : "=".repeat(4 - (str.length % 4));
  const b64 = (str + pad).replace(/-/g, "+").replace(/_/g, "/");
  return Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

async function hmacSha256Hex(key: string, data: string): Promise<string> {
  const enc = new TextEncoder();
  const cryptoKey = await crypto.subtle.importKey(
    "raw",
    enc.encode(key),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", cryptoKey, enc.encode(data));
  return bytesToHex(new Uint8Array(sig));
}

function timingSafeEq(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let res = 0;
  for (let i = 0; i < a.length; i++) res |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return res === 0;
}

function htmlPage(title: string, body: string, color = "#16a34a"): Response {
  const html = `<!doctype html>
<html><head><meta charset="utf-8"><title>${title}</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
  body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;
       background:#f8fafc;color:#0f172a;margin:0;min-height:100vh;
       display:flex;align-items:center;justify-content:center;padding:24px}
  .card{background:#fff;border-radius:16px;box-shadow:0 10px 30px rgba(0,0,0,.08);
        padding:40px;max-width:480px;text-align:center}
  .badge{display:inline-block;width:64px;height:64px;border-radius:50%;
         background:${color};color:#fff;font-size:32px;line-height:64px;margin-bottom:16px}
  h1{font-size:22px;margin:0 0 8px}
  p{color:#475569;line-height:1.5;margin:8px 0}
  a{color:#0ea5e9;text-decoration:none;font-weight:500}
</style></head>
<body><div class="card"><div class="badge">${color === "#16a34a" ? "✓" : color === "#dc2626" ? "✕" : "!"}</div>
<h1>${title}</h1>${body}
<p style="margin-top:24px"><a href="https://presaleproperties.com/admin/leads">Open admin dashboard →</a></p>
</div></body></html>`;
  return new Response(html, {
    status: 200,
    headers: { ...corsHeaders, "Content-Type": "text/html; charset=utf-8" },
  });
}

serve(async (req: Request): Promise<Response> => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const url = new URL(req.url);
    const token = url.searchParams.get("token");
    if (!token) {
      return htmlPage("Invalid link", "<p>Missing token.</p>", "#dc2626");
    }

    const [payloadB64, sig] = token.split(".");
    if (!payloadB64 || !sig) {
      return htmlPage("Invalid link", "<p>Malformed token.</p>", "#dc2626");
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

    // Verify signature
    const expectedSig = await hmacSha256Hex(serviceKey, payloadB64);
    if (!timingSafeEq(sig, expectedSig)) {
      return htmlPage(
        "Invalid signature",
        "<p>This link has been tampered with or was not generated by us.</p>",
        "#dc2626",
      );
    }

    // Decode + parse payload
    let payload: { leadId: string; action: string; exp: number };
    try {
      payload = JSON.parse(new TextDecoder().decode(b64urlDecode(payloadB64)));
    } catch {
      return htmlPage("Invalid link", "<p>Could not parse token.</p>", "#dc2626");
    }

    if (payload.exp && payload.exp * 1000 < Date.now()) {
      return htmlPage(
        "Link expired",
        "<p>This approval link has expired. Please use the admin dashboard.</p>",
        "#f59e0b",
      );
    }

    if (payload.action !== "approve" && payload.action !== "reject") {
      return htmlPage("Invalid action", "<p>Unknown action.</p>", "#dc2626");
    }

    const admin = createClient(supabaseUrl, serviceKey);
    const { data: lead, error: leadErr } = await admin
      .from("project_leads")
      .select("id, project_id, approval_status, name, email")
      .eq("id", payload.leadId)
      .maybeSingle();

    if (leadErr || !lead) {
      return htmlPage("Lead not found", "<p>This lead no longer exists.</p>", "#dc2626");
    }

    if (lead.approval_status !== "pending") {
      return htmlPage(
        "Already actioned",
        `<p>This lead is already <strong>${lead.approval_status}</strong>. No change made.</p>`,
        "#f59e0b",
      );
    }

    const newStatus = payload.action === "approve" ? "approved" : "rejected";
    const { error: updateErr } = await admin
      .from("project_leads")
      .update({
        approval_status: newStatus,
        approved_at: new Date().toISOString(),
        rejection_reason:
          payload.action === "reject" ? "Rejected via email link" : null,
      })
      .eq("id", payload.leadId);
    if (updateErr) throw updateErr;

    let autoResponseFired = false;
    if (payload.action === "approve") {
      try {
        const res = await fetch(
          `${supabaseUrl}/functions/v1/send-lead-autoresponse`,
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${serviceKey}`,
            },
            body: JSON.stringify({
              leadId: payload.leadId,
              projectId: lead.project_id,
              _approvedByAdmin: true,
            }),
          },
        );
        autoResponseFired = res.ok;
        if (res.ok) {
          await admin
            .from("project_leads")
            .update({ auto_response_sent_at: new Date().toISOString() })
            .eq("id", payload.leadId);
        }
      } catch (err) {
        console.error("[approve-lead-link] auto-response failed:", err);
      }
    }

    if (payload.action === "approve") {
      return htmlPage(
        "Lead approved ✓",
        `<p><strong>${lead.name ?? lead.email}</strong> has been approved.</p>
         <p>${autoResponseFired ? "Auto-response email sent." : "⚠️ Auto-response failed — check the dashboard."}</p>`,
        "#16a34a",
      );
    }
    return htmlPage(
      "Lead rejected",
      `<p><strong>${lead.name ?? lead.email}</strong> has been marked rejected. No email was sent.</p>`,
      "#dc2626",
    );
  } catch (err) {
    console.error("[approve-lead-link] error:", err);
    return htmlPage(
      "Something went wrong",
      `<p>${err instanceof Error ? err.message : "Unknown error"}</p>`,
      "#dc2626",
    );
  }
});
